export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAILURE = "AUTH_FAILURE";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const AUTH_USER_LOADED = "AUTH_USER_LOADED";

export const USERS_LOADING_START = "USERS_LOADING_START";
export const USERS_LOADING_SUCCESS = "USERS_LOADING_SUCCESS";
export const USERS_LOADING_FAILURE = "USERS_LOADING_FAILURE";

export const STORIES_LOADING_START = "STORIES_LOADING_START";
export const STORIES_LOADING_SUCCESS = "STORIES_LOADING_SUCCESS";
export const STORIES_LOADING_FAILURE = "STORIES_LOADING_FAILURE";

export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";
export const HIDE_ALERT = "HIDE_ALERT";
